### ISSUE TITLE
Mod wont load automatically when using docker-compose

### ISSUE THREAD

**Issue by RuofengX** [GedasFX/tmodloader#2]
As the title said.  

## My solution  

Run docker commond with `setup` params first, then using docker-compose.yml file to start.

**Comment by GedasFX** [comment]
Hey can you show the bash commands used? You may have not mounted the correct volume.

**Comment by RuofengX** [comment]
I used docker-compose to run first time(with empty data folder), container ended up with error saying that there is no MyWorld file.  
So i read the serverconfig.txt file, and add line `autocreate=3` to it. BTW the link in **serverconfig.txt line2** is outdated maybe.  

Then I add mod to tModloader_data/Mods, and start with `sudo docker-compose up`,  my mod didn't show up in my server.  

Then I just tried using docker setup command, and everything works.  
But still, tty and my keyboard input is not working in docker attaching mode, I opened another #3
